// ==================== TLC Calisthenics — Full Exercise Library ====================
// Merged: existing skills (with images) + new exercises from spec
// Ab Wheel Rollout: REMOVED per equipment policy

import type { Exercise } from './types';

// Existing skill images
import frogStandImg from '@/assets/skills/frog-stand.jpg';
import lSitImg from '@/assets/skills/l-sit.jpg';
import headstandImg from '@/assets/skills/headstand.jpg';
import pistolSquatImg from '@/assets/skills/pistol-squat.jpg';
import handstandImg from '@/assets/skills/handstand.jpg';
import skinTheCatImg from '@/assets/skills/skin-the-cat.jpg';
import pulloverImg from '@/assets/skills/pullover.jpg';
import tigerBendImg from '@/assets/skills/tiger-bend.jpg';
import clutchFlagImg from '@/assets/skills/clutch-flag.jpg';
import elbowLeverImg from '@/assets/skills/elbow-lever.jpg';
import needleImg from '@/assets/skills/needle.jpg';
import bentArmHandstandImg from '@/assets/skills/bent-arm-handstand.jpg';
import singleArmElbowLeverImg from '@/assets/skills/single-arm-elbow-lever.jpg';
import plancheLeanImg from '@/assets/skills/planche-lean.jpg';
import tuckPlancheImg from '@/assets/skills/tuck-planche.jpg';

export const exercises: Exercise[] = [
  // ==================== CORE ====================
  {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    category: 'core',
    difficulty: 'easy',
    muscles: ['Core', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['compression', 'planche', 'handstand', 'general'],
    shortPurpose: 'Foundation for every straight-body skill.',
    description: 'The hollow body is the shape that transfers to handstands, levers, and planche. Master this first.',
    doThis: { setsRange: '3–4', timeSecRange: '20–45s', restSecRange: '45–60s' },
    cueStack: ['Lower back glued to floor', 'Ribs pulled down', 'Arms by ears, biceps covering'],
    failSigns: ['Lower back lifts off floor', 'Neck straining forward', 'Legs shaking uncontrollably'],
    regressTo: [],
    progressTo: ['l-sit', 'planche-lean'],
    needsUpload: true,
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    difficulty: 'easy',
    muscles: ['Core', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Anti-extension baseline.',
    description: 'Forearm plank with intent. Squeeze everything—this is practice for maintaining tension under load.',
    doThis: { setsRange: '3', timeSecRange: '30–60s', restSecRange: '45s' },
    cueStack: ['Squeeze glutes', 'Pull elbows toward toes', 'Breathe behind the brace'],
    failSigns: ['Hips sagging', 'Butt piking up', 'Holding breath'],
    regressTo: [],
    progressTo: ['hollow-body-hold'],
    needsUpload: true,
  },
  {
    id: 'l-sit',
    name: 'L-Sit',
    category: 'core',
    difficulty: 'intermediate',
    muscles: ['Core', 'Hip Flexors', 'Triceps'],
    equipment: ['floor', 'parallettes'],
    tracks: ['compression', 'general'],
    shortPurpose: 'Compression strength for planche and press.',
    description: 'A fundamental static hold that develops incredible core strength and hip flexor endurance.',
    image: lSitImg,
    thumbnailUrl: 'https://i.ytimg.com/vi/cu0fHp8HCDo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=cu0fHp8HCDo',
    doThis: { setsRange: '4–5', timeSecRange: '10–30s', restSecRange: '60s' },
    cueStack: ['Depress shoulders hard', 'Point toes', 'Push floor away'],
    failSigns: ['Shoulders creeping to ears', 'Legs dropping below parallel', 'Bent knees (unless regressing)'],
    regressTo: ['tuck-sit', 'hollow-body-hold'],
    progressTo: [],
  },
  {
    id: 'dragon-flag',
    name: 'Dragon Flag',
    category: 'core',
    difficulty: 'advanced',
    muscles: ['Core', 'Lats', 'Hip Flexors'],
    equipment: ['floor', 'chair'],
    tracks: ['general'],
    shortPurpose: 'Full-body anti-extension under gravity.',
    description: 'Made famous by Bruce Lee. Keep the body as one unit—no bending at the hips.',
    doThis: { setsRange: '3–4', repsRange: '3–8', restSecRange: '90s' },
    cueStack: ['Grip bench behind head', 'Lower as one rigid line', 'Control the negative'],
    failSigns: ['Hips bending', 'Lower back arching', 'Dropping too fast'],
    regressTo: ['hollow-body-hold'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    difficulty: 'intermediate',
    muscles: ['Core', 'Hip Flexors', 'Grip'],
    equipment: ['pull-up bar'],
    tracks: ['compression', 'general'],
    shortPurpose: 'Active compression + grip under load.',
    description: 'Hang from a bar, raise straight legs to horizontal or above. No swinging.',
    doThis: { setsRange: '3–4', repsRange: '6–12', restSecRange: '60s' },
    cueStack: ['Dead hang start', 'Legs straight', 'Control the descent'],
    failSigns: ['Swinging/kipping', 'Bent knees at top', 'Losing grip'],
    regressTo: ['hollow-body-hold'],
    progressTo: ['toes-to-bar'],
    needsUpload: true,
  },

  // ==================== LEGS ====================
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'legs',
    difficulty: 'easy',
    muscles: ['Quadriceps', 'Glutes', 'Core'],
    equipment: ['floor'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Fundamental lower body pattern.',
    description: 'Full depth squat with control. Heels stay planted, chest stays tall.',
    doThis: { setsRange: '3–4', repsRange: '10–20', restSecRange: '60s' },
    cueStack: ['Feet shoulder width', 'Knees track toes', 'Full depth'],
    failSigns: ['Heels lifting', 'Knees caving in', 'Forward lean'],
    regressTo: [],
    progressTo: ['bulgarian-split-squat', 'pistol-squat'],
    needsUpload: true,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    difficulty: 'beginner',
    muscles: ['Quadriceps', 'Glutes', 'Hip Flexors'],
    equipment: ['floor', 'chair'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Unilateral leg strength + hip mobility.',
    description: 'Rear foot elevated on a bench. Drop the back knee straight down.',
    doThis: { setsRange: '3–4', repsRange: '8–12 each', restSecRange: '60s' },
    cueStack: ['Upright torso', 'Front knee over toes', 'Control the bottom'],
    failSigns: ['Torso collapsing forward', 'Front heel lifting', 'Losing balance every rep'],
    regressTo: ['bodyweight-squat'],
    progressTo: ['pistol-squat', 'shrimp-squat'],
    needsUpload: true,
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'legs',
    difficulty: 'easy',
    muscles: ['Calves'],
    equipment: ['floor'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Ankle strength for balance skills.',
    description: 'Single or double leg. Full range: heel below toes to max plantar flexion.',
    thumbnailUrl: 'https://i.ytimg.com/vi/_5R7wFS6l9o/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=_5R7wFS6l9o',
    doThis: { setsRange: '3', repsRange: '15–25', restSecRange: '45s' },
    cueStack: ['Full range of motion', 'Pause at top', 'Slow negative'],
    failSigns: ['Bouncing', 'Partial range', 'Shifting weight to one side'],
    regressTo: [],
    progressTo: [],
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    category: 'legs',
    difficulty: 'intermediate',
    muscles: ['Hamstrings', 'Glutes'],
    equipment: ['floor'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Eccentric hamstring strength.',
    description: 'Kneel, anchor feet, lower your body forward under control. The negative is the exercise.',
    thumbnailUrl: 'https://i.ytimg.com/vi/DQQleh4xUjU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=DQQleh4xUjU',
    doThis: { setsRange: '3–4', repsRange: '3–8', restSecRange: '90s' },
    cueStack: ['Hips extended throughout', 'Lower as slowly as possible', 'Catch yourself at the bottom'],
    failSigns: ['Hips breaking/bending', 'Falling uncontrolled', 'Using arms to push back up'],
    regressTo: ['bodyweight-squat'],
    progressTo: [],
  },
  {
    id: 'pistol-squat',
    name: 'Pistol Squat',
    category: 'legs',
    difficulty: 'intermediate',
    muscles: ['Quadriceps', 'Glutes', 'Core'],
    equipment: ['floor'],
    tracks: ['legs'],
    shortPurpose: 'Single-leg strength + balance mastery.',
    description: 'The ultimate single-leg strength exercise that builds leg power, balance, and mobility.',
    image: pistolSquatImg,
    thumbnailUrl: 'https://i.ytimg.com/vi/2YW5b4U7d2c/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=2YW5b4U7d2c',
    doThis: { setsRange: '3–4', repsRange: '3–8 each', restSecRange: '90s' },
    cueStack: ['Arms forward for counterbalance', 'Heel stays planted', 'Stand up without wobble'],
    failSigns: ['Heel lifting', 'Knee caving inward', 'Falling at bottom'],
    regressTo: ['bulgarian-split-squat', 'bodyweight-squat'],
    progressTo: ['shrimp-squat'],
  },
  {
    id: 'shrimp-squat',
    name: 'Shrimp Squat',
    category: 'legs',
    difficulty: 'advanced',
    muscles: ['Quadriceps', 'Glutes', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['legs'],
    shortPurpose: 'Advanced single-leg with rear-foot hold.',
    description: 'Grab rear foot behind you and squat on one leg. Demands quad strength and balance.',
    doThis: { setsRange: '3', repsRange: '3–6 each', restSecRange: '90s' },
    cueStack: ['Hold rear foot', 'Stay upright', 'Knee touches floor gently'],
    failSigns: ['Losing grip on rear foot', 'Falling forward', 'Knee slamming down'],
    regressTo: ['pistol-squat', 'bulgarian-split-squat'],
    progressTo: [],
    needsUpload: true,
  },

  // ==================== MOBILITY ====================
  {
    id: 'bridge-pose',
    name: 'Bridge Pose',
    category: 'yoga',
    difficulty: 'beginner',
    muscles: ['Spine', 'Shoulders', 'Glutes'],
    equipment: ['floor'],
    tracks: ['general', 'yoga-flow'],
    shortPurpose: 'Spinal extension + shoulder opening.',
    description: 'Glute bridge to full bridge progression. Open the front body safely.',
    doThis: { setsRange: '3', timeSecRange: '15–30s', restSecRange: '60s' },
    cueStack: ['Push through hands', 'Open chest', 'Breathe into the stretch'],
    failSigns: ['Shoulders not over wrists', 'Pain in lower back', 'Holding breath'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'cat-cow-stretch',
    name: 'Cat-Cow Stretch',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Spine', 'Core'],
    equipment: ['floor'],
    tracks: ['general', 'yoga-flow'],
    shortPurpose: 'Spinal articulation warm-up.',
    description: 'Flow between spinal flexion and extension. Breath-driven, slow.',
    doThis: { setsRange: '2–3', repsRange: '8–12', restSecRange: '30s' },
    cueStack: ['Inhale: arch', 'Exhale: round', 'Move one vertebra at a time'],
    failSigns: ['Rushing', 'No breath coordination', 'Neck hyperextending'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'cobra-pose',
    name: 'Cobra Pose',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Spine', 'Core', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['general', 'yoga-flow'],
    shortPurpose: 'Gentle spinal extension.',
    description: 'Lie prone, press up through hands keeping hips grounded. Open the chest.',
    doThis: { setsRange: '2–3', timeSecRange: '15–30s', restSecRange: '30s' },
    cueStack: ['Hips stay on floor', 'Elbows slightly bent', 'Look forward, not up'],
    failSigns: ['Hips lifting', 'Shoulders at ears', 'Lower back pain'],
    regressTo: [],
    progressTo: ['bridge-pose'],
    needsUpload: true,
  },
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    category: 'mobility',
    difficulty: 'easy',
    muscles: ['Hips', 'Ankles', 'Core'],
    equipment: ['floor'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Hip + ankle mobility baseline.',
    description: 'Sit in the bottom of a squat. Heels down, chest up. Breathe and explore the range.',
    doThis: { setsRange: '2–3', timeSecRange: '30–90s', restSecRange: '30s' },
    cueStack: ['Heels flat', 'Knees out', 'Chest tall'],
    failSigns: ['Heels lifting', 'Rounding completely', 'Holding breath'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'downward-dog',
    name: 'Downward Dog',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Shoulders', 'Hamstrings', 'Calves'],
    equipment: ['floor'],
    tracks: ['handstand', 'general', 'yoga-flow'],
    shortPurpose: 'Shoulder overhead prep + posterior chain.',
    description: 'Inverted V shape. Push hips high, heels toward floor. Active shoulders.',
    doThis: { setsRange: '2–3', timeSecRange: '30–60s', restSecRange: '30s' },
    cueStack: ['Push floor away', 'Externally rotate arms', 'Pedal heels'],
    failSigns: ['Shoulders dumping', 'Rounded upper back', 'Locked knees with pain'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose',
    category: 'yoga',
    difficulty: 'beginner',
    muscles: ['Hips', 'Glutes', 'Piriformis'],
    equipment: ['floor'],
    tracks: ['general', 'yoga-flow'],
    shortPurpose: 'Deep hip external rotation stretch.',
    description: 'Front leg bent, back leg extended. Fold forward for intensity. Breathe into the hip.',
    doThis: { setsRange: '2–3', timeSecRange: '45–90s each', restSecRange: '30s' },
    cueStack: ['Square hips', 'Fold forward slowly', 'Breathe into the stretch'],
    failSigns: ['Knee pain in front leg', 'Hip rolling open', 'Forcing depth'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'shoulder-dislocate',
    name: 'Shoulder Dislocate',
    category: 'mobility',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Chest'],
    equipment: ['towel'],
    tracks: ['handstand', 'rings', 'general'],
    shortPurpose: 'Shoulder ROM for overhead + behind-back positions.',
    description: 'Wide grip on stick/towel, pass it over your head and behind your back. Gradual narrowing.',
    doThis: { setsRange: '2–3', repsRange: '8–12', restSecRange: '30s' },
    cueStack: ['Wide grip to start', 'Straight arms throughout', 'Narrow grip as mobility improves'],
    failSigns: ['Bending elbows', 'Pain in front of shoulder', 'Jerking through sticky spots'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'mobility',
    difficulty: 'beginner',
    muscles: ['Hips', 'Thoracic Spine', 'Hamstrings'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Full-body mobility in one flow.',
    description: 'Lunge, rotate, reach. Hits hips, T-spine, hamstrings, and groin in a single sequence.',
    doThis: { setsRange: '2–3', repsRange: '5–8 each side', restSecRange: '30s' },
    cueStack: ['Deep lunge first', 'Rotate and reach to sky', 'Straighten front leg for hamstring'],
    failSigns: ['Rushing through', 'No thoracic rotation', 'Back knee slamming down'],
    regressTo: [],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'needle',
    name: 'Needle',
    category: 'mobility',
    difficulty: 'advanced',
    muscles: ['Hamstrings', 'Hip Flexors', 'Lower Back'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Extreme standing split flexibility.',
    description: 'An extreme flexibility skill showcasing total hamstring and hip mobility.',
    image: needleImg,
    doThis: { setsRange: '3', timeSecRange: '10–30s each', restSecRange: '60s' },
    cueStack: ['Stand on one leg', 'Raise back leg straight behind', 'Reach for standing ankle'],
    failSigns: ['Bending standing knee', 'Rounding spine', 'Forcing range with bounce'],
    regressTo: [],
    progressTo: [],
  },

  // ==================== PULL ====================
  {
    id: 'australian-row',
    name: 'Australian Row',
    category: 'pull',
    difficulty: 'beginner',
    muscles: ['Back', 'Biceps', 'Core'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength', 'general'],
    shortPurpose: 'Horizontal pull foundation.',
    description: 'Inverted row under a low bar. Body stays straight. Pull chest to bar.',
    doThis: { setsRange: '3–4', repsRange: '8–15', restSecRange: '60s' },
    cueStack: ['Body straight as a plank', 'Pull shoulder blades together', 'Chest to bar'],
    failSigns: ['Hips sagging', 'Chin jutting forward', 'Not reaching full ROM'],
    regressTo: [],
    progressTo: ['chin-up', 'pull-up'],
    needsUpload: true,
  },
  {
    id: 'chin-up',
    name: 'Chin-up',
    category: 'pull',
    difficulty: 'beginner',
    muscles: ['Biceps', 'Back', 'Core'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength'],
    shortPurpose: 'Supinated pull—biceps-emphasized.',
    description: 'Underhand grip. Pull chin over bar. Full dead hang at bottom.',
    doThis: { setsRange: '3–4', repsRange: '4–10', restSecRange: '90s' },
    cueStack: ['Full dead hang start', 'Chin clears bar', 'Control the descent'],
    failSigns: ['Kipping', 'Half reps', 'Chicken-necking'],
    regressTo: ['australian-row'],
    progressTo: ['pull-up'],
    needsUpload: true,
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    category: 'pull',
    difficulty: 'intermediate',
    muscles: ['Lats', 'Biceps', 'Core'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength'],
    shortPurpose: 'King of upper-body pulling.',
    description: 'Overhand grip, dead hang to chin over bar. No kipping. Full ROM.',
    doThis: { setsRange: '3–5', repsRange: '3–10', restSecRange: '90–120s' },
    cueStack: ['Dead hang start', 'Pull elbows to hips', 'Chin clears bar'],
    failSigns: ['Kipping/swinging', 'Half reps', 'Losing core tension'],
    regressTo: ['chin-up', 'australian-row'],
    progressTo: ['archer-pull-up'],
    needsUpload: true,
  },
  {
    id: 'archer-pull-up',
    name: 'Archer Pull-up',
    category: 'pull',
    difficulty: 'advanced',
    muscles: ['Lats', 'Biceps', 'Core'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength'],
    shortPurpose: 'Unilateral pulling toward one-arm.',
    description: 'Wide grip. Pull to one side while the other arm extends. Alternate sides.',
    doThis: { setsRange: '3–4', repsRange: '3–6 each', restSecRange: '120s' },
    cueStack: ['Pull to one hand', 'Other arm stays straight', 'Full dead hang between'],
    failSigns: ['Both arms pulling equally', 'Kipping', 'Losing control at bottom'],
    regressTo: ['pull-up'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'front-lever-raise',
    name: 'Front Lever Raise',
    category: 'pull',
    difficulty: 'advanced',
    muscles: ['Lats', 'Core', 'Biceps'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength'],
    shortPurpose: 'Dynamic front lever entry.',
    description: 'From dead hang, raise body to horizontal front lever position with straight arms.',
    doThis: { setsRange: '4–6', repsRange: '2–5', restSecRange: '120s' },
    cueStack: ['Straight arms', 'Depress shoulders', 'Stop at horizontal'],
    failSigns: ['Bending arms', 'Swinging into it', 'Not reaching horizontal'],
    regressTo: ['pull-up', 'skin-the-cat'],
    progressTo: ['front-lever'],
    needsUpload: true,
  },
  {
    id: 'muscle-up',
    name: 'Muscle-up',
    category: 'pull',
    difficulty: 'advanced',
    muscles: ['Lats', 'Chest', 'Triceps', 'Core'],
    equipment: ['pull-up bar', 'rings'],
    tracks: ['pull-strength', 'rings'],
    shortPurpose: 'Pull-to-push transition.',
    description: 'Explosive pull-up that transitions into a dip above the bar or rings.',
    doThis: { setsRange: '3–5', repsRange: '1–5', restSecRange: '120–180s' },
    cueStack: ['High pull', 'Fast transition', 'Lock out on top'],
    failSigns: ['Chicken winging', 'No height on pull', 'Elbow pain'],
    regressTo: ['pull-up', 'pullover'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'skin-the-cat',
    name: 'Skin The Cat',
    category: 'pull',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Lats', 'Core'],
    equipment: ['pull-up bar', 'rings'],
    tracks: ['rings', 'pull-strength'],
    shortPurpose: 'Shoulder mobility under load.',
    description: 'A dynamic shoulder mobility exercise that builds the foundation for advanced ring work.',
    image: skinTheCatImg,
    doThis: { setsRange: '3–4', repsRange: '3–5', restSecRange: '90s' },
    cueStack: ['Tuck knees first', 'Roll through slowly', 'Control German hang'],
    failSigns: ['Dropping into German hang', 'Losing grip', 'Forcing range of motion'],
    regressTo: ['shoulder-dislocate'],
    progressTo: ['back-lever'],
  },
  {
    id: 'pullover',
    name: 'Pullover',
    category: 'pull',
    difficulty: 'intermediate',
    muscles: ['Back', 'Biceps', 'Core'],
    equipment: ['pull-up bar'],
    tracks: ['pull-strength', 'general'],
    shortPurpose: 'Bar transition skill.',
    description: 'A fundamental bar transition skill that combines pulling strength with hip flexibility.',
    image: pulloverImg,
    doThis: { setsRange: '3–4', repsRange: '3–8', restSecRange: '90s' },
    cueStack: ['Pull high first', 'Stay close to bar', 'Control the roll'],
    failSigns: ['Swinging wildly', 'Elbows flaring wide', 'Falling over the top'],
    regressTo: ['pull-up'],
    progressTo: ['muscle-up'],
  },

  // ==================== PUSH ====================
  {
    id: 'push-up',
    name: 'Push-up',
    category: 'push',
    difficulty: 'easy',
    muscles: ['Chest', 'Triceps', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['planche', 'general'],
    shortPurpose: 'The universal push pattern.',
    description: 'Hands shoulder-width, straight body, chest to floor and back up. Quality over quantity.',
    doThis: { setsRange: '3–4', repsRange: '8–20', restSecRange: '60s' },
    cueStack: ['Body one straight line', 'Elbows ~45°', 'Full ROM'],
    failSigns: ['Hips sagging', 'Elbows flaring 90°', 'Partial reps'],
    regressTo: [],
    progressTo: ['diamond-push-up', 'pseudo-planche-push-up', 'archer-push-up'],
    needsUpload: true,
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-up',
    category: 'push',
    difficulty: 'beginner',
    muscles: ['Triceps', 'Chest', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Triceps-heavy push.',
    description: 'Hands together forming a diamond. Emphasizes triceps and inner chest.',
    doThis: { setsRange: '3–4', repsRange: '6–15', restSecRange: '60s' },
    cueStack: ['Hands touching under chest', 'Elbows brush ribs', 'Full lockout'],
    failSigns: ['Elbows flaring wide', 'Hips sagging', 'Not touching chest to hands'],
    regressTo: ['push-up'],
    progressTo: ['archer-push-up'],
    needsUpload: true,
  },
  {
    id: 'archer-push-up',
    name: 'Archer Push-up',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Unilateral push progression.',
    description: 'Wide hands. Lower to one side while other arm extends straight. Alternate.',
    doThis: { setsRange: '3–4', repsRange: '4–8 each', restSecRange: '90s' },
    cueStack: ['Wide hand placement', 'Lower to working arm', 'Straight arm fully extends'],
    failSigns: ['Bending the extended arm', 'Rotating torso', 'Partial range'],
    regressTo: ['diamond-push-up', 'push-up'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-up',
    category: 'push',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Triceps'],
    equipment: ['floor'],
    tracks: ['handstand', 'general'],
    shortPurpose: 'Overhead pressing foundation.',
    description: 'Hips high in an inverted V. Press straight down and up. Builds HSPU strength.',
    doThis: { setsRange: '3–4', repsRange: '6–12', restSecRange: '60–90s' },
    cueStack: ['Hips stay high', 'Head between arms', 'Full lockout'],
    failSigns: ['Hips dropping', 'Elbows flaring', 'Incomplete ROM'],
    regressTo: ['push-up'],
    progressTo: ['handstand-push-up'],
    needsUpload: true,
  },
  {
    id: 'handstand-push-up',
    name: 'Handstand Push-up',
    category: 'push',
    difficulty: 'advanced',
    muscles: ['Shoulders', 'Triceps', 'Core'],
    equipment: ['wall'],
    tracks: ['handstand'],
    shortPurpose: 'Overhead pressing at bodyweight.',
    description: 'Wall-supported or freestanding. Head to floor and press back to full lockout.',
    instagramUrl: 'https://www.instagram.com/p/DSlL7m3DCGN/',
    doThis: { setsRange: '3–5', repsRange: '2–8', restSecRange: '120s' },
    cueStack: ['Hands shoulder-width', 'Head touches floor', 'Full lockout at top'],
    failSigns: ['Kipping with hips', 'Arching excessively', 'Not reaching full ROM'],
    regressTo: ['pike-push-up'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'parallel-bar-dip',
    name: 'Parallel Bar Dip',
    category: 'push',
    difficulty: 'beginner',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['chair', 'parallettes'],
    tracks: ['rings', 'general'],
    shortPurpose: 'Vertical push power.',
    description: 'Dip between parallel bars or chairs. Shoulders below elbows at the bottom.',
    doThis: { setsRange: '3–4', repsRange: '5–12', restSecRange: '90s' },
    cueStack: ['Lean slightly forward', 'Shoulders below elbows', 'Full lockout at top'],
    failSigns: ['Shallow range', 'Shoulders shrugging', 'Excessive forward lean'],
    regressTo: ['push-up'],
    progressTo: ['ring-dip'],
    needsUpload: true,
  },
  {
    id: 'tiger-bend-pushup',
    name: 'Tiger Bend Push Up',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Triceps', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['handstand', 'general'],
    shortPurpose: 'Forearm-to-hand press for HSPU.',
    description: 'An advanced push-up variation that builds tricep strength for planche and handstand push-ups.',
    image: tigerBendImg,
    doThis: { setsRange: '3–4', repsRange: '3–8', restSecRange: '90s' },
    cueStack: ['Forearms to hands in one press', 'Body stays straight', 'Triceps do the work'],
    failSigns: ['Hips piking to cheat', 'Partial press', 'Elbow pain'],
    regressTo: ['diamond-push-up'],
    progressTo: ['handstand-push-up'],
  },

  // ==================== PLANCHE TRACK ====================
  {
    id: 'planche-lean',
    name: 'Planche Lean',
    category: 'push',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Wrists', 'Serratus', 'Core'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'Entry-level planche leverage.',
    description: 'Hands slightly behind shoulders. Lock elbows. Push floor away and lean forward while staying hollow.',
    image: plancheLeanImg,
    thumbnailUrl: 'https://i.ytimg.com/vi/xLPP33cZVI4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=xLPP33cZVI4',
    doThis: { setsRange: '5', timeSecRange: '10–25s', restSecRange: '60–90s' },
    cueStack: ['Elbows locked', 'Protract hard', 'Ribs to hips (hollow)'],
    failSigns: ['Bent elbows', 'Scap retraction', 'No forward lean'],
    regressTo: ['push-up'],
    progressTo: ['pseudo-planche-push-up', 'planche-plank'],
    coachNotes: {
      mechanic: 'Hands slightly behind shoulders. Lock elbows. Push the floor away (protract) and lean forward while staying hollow (ribs to hips).',
      brutality: 'You are fighting leverage. If you lose the lean, you lose the protocol. Small holds win.',
      watchOut: 'Bent elbows = instant fail. Reset, reduce lean.',
      recoveryVector: 'Forearm flush + gentle biceps tendon unload (easy stretch).',
    },
  },
  {
    id: 'pseudo-planche-push-up',
    name: 'Pseudo Planche Push-up',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Chest', 'Triceps', 'Core'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'Dynamic planche strength builder.',
    description: 'Hands slightly back. Lean forward before you descend. At the top: elbows lock + scap protraction + hollow stays tight.',
    doThis: { setsRange: '4', repsRange: '5–10', restSecRange: '90s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/i-gSmqe9tNw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=i-gSmqe9tNw',
    cueStack: ['Lean forward THEN descend', 'Lock elbows at top', 'Protract at top'],
    failSigns: ['No forward lean', 'Soft elbows at top', 'Losing hollow'],
    regressTo: ['planche-lean', 'push-up'],
    progressTo: ['tuck-planche'],
    coachNotes: {
      mechanic: 'Hands slightly back. Lean forward before you descend. At the top: elbows lock + scap protraction + hollow stays tight.',
      brutality: 'This is a push-up that punishes dishonesty. Lose the lean and you\'ve changed the exercise.',
      watchOut: 'Soft elbows at the top = stop the set and reset.',
      recoveryVector: 'Serratus release (ball) + wrist flexor stretch.',
    },
  },
  {
    id: 'planche-plank',
    name: 'Planche Plank',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Triceps', 'Core', 'Serratus'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'Straight-arm hold: tendon builder.',
    description: 'Elbows locked. Push floor away. Hollow body. Hold the line like you\'re freezing a screenshot.',
    doThis: { setsRange: '5', timeSecRange: '15–30s', restSecRange: '60–90s' },
    cueStack: ['Elbows locked hard', 'Max protraction', 'Hollow body maintained'],
    failSigns: ['Any elbow bend', 'Scap collapse', 'Hips sagging'],
    regressTo: ['planche-lean'],
    progressTo: ['tuck-planche'],
    needsUpload: true,
    coachNotes: {
      mechanic: 'Elbows locked. Push floor away. Hollow body. Hold the line like you\'re freezing a screenshot.',
      brutality: 'This is tendon work. It should feel intense without feeling sketchy. Respect the line.',
      watchOut: 'If elbows bend even 1 degree, you just left planche training.',
      recoveryVector: 'Cold water forearm dip (optional) + gentle biceps stretch.',
    },
  },
  {
    id: 'tuck-planche',
    name: 'Tuck Planche',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Triceps', 'Serratus'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'First true planche float.',
    description: 'From a strong lean: tuck knees tight to chest, shoulders forward, elbows locked, protract hard.',
    image: tuckPlancheImg,
    thumbnailUrl: 'https://i.ytimg.com/vi/qvWvfZuUN4k/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=qvWvfZuUN4k',
    doThis: { setsRange: '8–10', timeSecRange: '5–12s', restSecRange: '60–90s' },
    cueStack: ['Knees tight to chest', 'Elbows locked', 'Protract max'],
    failSigns: ['Jumping into it', 'Losing protraction', 'Wrist pain'],
    regressTo: ['planche-plank', 'pseudo-planche-push-up'],
    progressTo: ['advanced-tuck-planche'],
    coachNotes: {
      mechanic: 'From a strong lean: tuck knees tight to chest, shoulders forward, elbows locked, protract hard. Small float, clean exit.',
      brutality: 'This is where your nervous system panics. Stay calm. Small holds are the correct dose.',
      watchOut: 'Jumping into it = wrist tax. Float only.',
      recoveryVector: 'Forearm massage + scap wall slides.',
    },
  },
  {
    id: 'advanced-tuck-planche',
    name: 'Advanced Tuck Planche',
    category: 'push',
    difficulty: 'advanced',
    muscles: ['Shoulders', 'Core', 'Triceps'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'Hips higher, knees extending.',
    description: 'Tuck planche with hips raised higher and knees extending slightly. The bridge to straddle.',
    doThis: { setsRange: '6–8', timeSecRange: '5–10s', restSecRange: '90–120s' },
    cueStack: ['Hips above shoulders', 'Extend knees slightly', 'Protract throughout'],
    failSigns: ['Dropping hips', 'Bending elbows', 'Losing hollow'],
    regressTo: ['tuck-planche'],
    progressTo: ['straddle-planche'],
    needsUpload: true,
  },
  {
    id: 'straddle-planche',
    name: 'Straddle Planche',
    category: 'push',
    difficulty: 'master',
    muscles: ['Shoulders', 'Core', 'Triceps'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'Open-leg full planche hold.',
    description: 'Legs spread wide, body horizontal, straight arms. The culmination of months of work.',
    doThis: { setsRange: '5–8', timeSecRange: '3–10s', restSecRange: '120–180s' },
    cueStack: ['Spread legs wide', 'Protract hard', 'Elbows locked'],
    failSigns: ['Arms bending', 'Hips dropping', 'Legs closing'],
    regressTo: ['advanced-tuck-planche'],
    progressTo: ['full-planche'],
    needsUpload: true,
  },
  {
    id: 'full-planche',
    name: 'Planche',
    category: 'skills',
    difficulty: 'master',
    muscles: ['Shoulders', 'Core', 'Triceps', 'Full Body'],
    equipment: ['floor'],
    tracks: ['planche'],
    shortPurpose: 'The full planche. Legs together, body horizontal.',
    description: 'Legs together, body perfectly horizontal, arms straight. Years of work distilled into one hold.',
    doThis: { setsRange: '5–8', timeSecRange: '2–8s', restSecRange: '180s' },
    cueStack: ['Legs together', 'Full protraction', 'Elbows locked'],
    failSigns: ['Any elbow bend', 'Hips dropping', 'Losing hollow'],
    regressTo: ['straddle-planche'],
    progressTo: [],
    needsUpload: true,
  },

  // ==================== HANDSTAND TRACK ====================
  {
    id: 'chest-to-wall-handstand',
    name: 'Chest-to-Wall Handstand',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Core', 'Wrists'],
    equipment: ['wall'],
    tracks: ['handstand'],
    shortPurpose: 'Wall drill for handstand line.',
    description: 'Face the wall, walk feet up. Chest close to wall. Build the vertical line and shoulder endurance.',
    doThis: { setsRange: '4–5', timeSecRange: '20–45s', restSecRange: '60–90s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/olA58oW-21A/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=olA58oW-21A',
    cueStack: ['Fingers spread, grip floor', 'Push floor away (shrug)', 'Ribs in, butt squeezed'],
    failSigns: ['Banana back', 'Shoulders dumping', 'Holding breath'],
    regressTo: ['downward-dog', 'pike-push-up'],
    progressTo: ['hs-shrugs', 'wall-pull-aways'],
  },
  {
    id: 'hs-shrugs',
    name: 'Handstand Shrugs',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Traps', 'Core'],
    equipment: ['wall'],
    tracks: ['handstand'],
    shortPurpose: 'Active shoulder elevation strength.',
    description: 'In chest-to-wall HS, shrug up and depress down. Builds the active support.',
    doThis: { setsRange: '3–4', repsRange: '8–12', restSecRange: '60s' },
    cueStack: ['Shrug UP hard', 'Depress with control', 'Stay aligned'],
    failSigns: ['Arching during movement', 'Rushed reps', 'Losing wall contact'],
    regressTo: ['chest-to-wall-handstand'],
    progressTo: ['wall-pull-aways', 'freestanding-handstand'],
    needsUpload: true,
  },
  {
    id: 'wall-pull-aways',
    name: 'Wall Pull-Aways',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Wrists'],
    equipment: ['wall'],
    tracks: ['handstand'],
    shortPurpose: 'Balance entry from wall.',
    description: 'In chest-to-wall HS, gently pull feet off wall and balance for 2–5 seconds. Return to wall.',
    doThis: { setsRange: '5–8', timeSecRange: '2–5s per attempt', restSecRange: '30–60s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/q6Xcsw0O23I/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=q6Xcsw0O23I',
    cueStack: ['Gentle toe-off', 'Fingertip pressure for balance', 'Return to wall with control'],
    failSigns: ['Kicking off aggressively', 'Arching to compensate', 'No controlled return'],
    regressTo: ['hs-shrugs', 'chest-to-wall-handstand'],
    progressTo: ['freestanding-handstand'],
  },
  {
    id: 'freestanding-handstand',
    name: 'Freestanding Handstand',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Shoulders', 'Core', 'Wrists', 'Triceps'],
    equipment: ['floor'],
    tracks: ['handstand'],
    shortPurpose: 'Freestanding balance mastery.',
    description: 'The king of bodyweight skills. A freestanding handstand demonstrates mastery of balance and body control.',
    image: handstandImg,
    doThis: { setsRange: '8–12 attempts', timeSecRange: '5–30s holds', restSecRange: '30–60s' },
    cueStack: ['Push floor away', 'Fingers grip for balance', 'Breathe and stack'],
    failSigns: ['Banana back', 'Not using fingers', 'Holding breath'],
    regressTo: ['wall-pull-aways', 'hs-shrugs'],
    progressTo: ['handstand-push-up'],
  },
  {
    id: 'headstand',
    name: 'Headstand',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Core', 'Neck'],
    equipment: ['floor'],
    tracks: ['handstand', 'general'],
    shortPurpose: 'Gateway inversion.',
    description: 'The gateway inversion that builds shoulder stability and body awareness for more advanced inversions.',
    image: headstandImg,
    doThis: { setsRange: '3–4', timeSecRange: '15–45s', restSecRange: '60s' },
    cueStack: ['Weight in forearms, not head', 'Core tight', 'Stack hips over shoulders'],
    failSigns: ['All weight on head', 'Arching back', 'Falling out uncontrolled'],
    regressTo: [],
    progressTo: ['chest-to-wall-handstand'],
  },

  // ==================== RINGS ====================
  {
    id: 'ring-support-hold',
    name: 'Ring Support Hold',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Triceps', 'Core'],
    equipment: ['rings'],
    tracks: ['rings'],
    shortPurpose: 'Ring stability baseline.',
    description: 'Hold yourself on top of rings with locked arms. Rings touching sides of body.',
    doThis: { setsRange: '4–5', timeSecRange: '15–30s', restSecRange: '60s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/31HMRQisaFU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=31HMRQisaFU',
    cueStack: ['Lock elbows', 'Depress shoulders', 'Rings touch body'],
    failSigns: ['Rings shaking uncontrollably', 'Elbows bending', 'Shoulders at ears'],
    regressTo: ['parallel-bar-dip'],
    progressTo: ['rto-support-hold', 'ring-dip'],
  },
  {
    id: 'rto-support-hold',
    name: 'RTO Support Hold',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Biceps', 'Core'],
    equipment: ['rings'],
    tracks: ['rings'],
    shortPurpose: 'Rings turned out—tendon prep.',
    description: 'Support hold with rings turned out 45–90°. Builds biceps tendon resilience.',
    doThis: { setsRange: '4–5', timeSecRange: '10–20s', restSecRange: '60–90s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/8gmyhBScTLk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=8gmyhBScTLk',
    cueStack: ['Turn rings out', 'Lock elbows', 'Stay tall'],
    failSigns: ['Rings turning back in', 'Elbows bending', 'Pain in biceps tendon'],
    regressTo: ['ring-support-hold'],
    progressTo: ['ring-dip'],
  },
  {
    id: 'ring-dip',
    name: 'Ring Dip',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Chest', 'Triceps', 'Shoulders'],
    equipment: ['rings'],
    tracks: ['rings'],
    shortPurpose: 'Ring push strength.',
    description: 'Full dip on rings. Deeper range than bars, higher instability demand.',
    doThis: { setsRange: '3–4', repsRange: '3–8', restSecRange: '90s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/RFODjZQos8E/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=RFODjZQos8E',
    cueStack: ['Turn rings out at top', 'Shoulders below elbows', 'Control the descent'],
    failSigns: ['Rings flaring out', 'Partial ROM', 'Shoulder pain'],
    regressTo: ['rto-support-hold', 'parallel-bar-dip'],
    progressTo: ['muscle-up'],
  },
  {
    id: 'ring-row',
    name: 'Ring Row',
    category: 'pull',
    difficulty: 'beginner',
    muscles: ['Back', 'Biceps', 'Core'],
    equipment: ['rings'],
    tracks: ['rings', 'pull-strength'],
    shortPurpose: 'Horizontal ring pull.',
    description: 'Inverted row on rings. Body straight, pull rings to chest.',
    doThis: { setsRange: '3–4', repsRange: '8–15', restSecRange: '60s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/bHO0A4ZF_Zg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=bHO0A4ZF_Zg',
    cueStack: ['Body straight', 'Pull rings to chest', 'Squeeze shoulder blades'],
    failSigns: ['Hips sagging', 'Partial pull', 'Chin jutting'],
    regressTo: [],
    progressTo: ['australian-row', 'pull-up'],
  },
  {
    id: 'false-grip-hold',
    name: 'False Grip Hold',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Forearms', 'Wrists', 'Grip'],
    equipment: ['rings'],
    tracks: ['rings'],
    shortPurpose: 'Grip position for muscle-up.',
    description: 'Hang from rings with wrists over the rings (false grip). Builds the grip for ring muscle-ups.',
    doThis: { setsRange: '4–6', timeSecRange: '10–20s', restSecRange: '60s' },
    cueStack: ['Wrist crease over ring', 'Grip hard', 'Depress shoulders'],
    failSigns: ['Slipping out of grip', 'Wrist pain', 'Shoulders at ears'],
    regressTo: ['ring-support-hold'],
    progressTo: ['muscle-up'],
    needsUpload: true,
  },

  // ==================== COMPRESSION TRACK ====================
  {
    id: 'tuck-sit',
    name: 'Tuck Sit',
    category: 'core',
    difficulty: 'beginner',
    muscles: ['Core', 'Hip Flexors'],
    equipment: ['floor', 'parallettes'],
    tracks: ['compression'],
    shortPurpose: 'L-sit regression—build compression.',
    description: 'Lift off floor with tucked knees. Shoulders depressed, arms straight.',
    doThis: { setsRange: '4–5', timeSecRange: '10–20s', restSecRange: '45–60s' },
    cueStack: ['Depress shoulders', 'Knees to chest', 'Arms straight'],
    failSigns: ['Shoulders shrugging', 'Not lifting off floor', 'Holding breath'],
    regressTo: ['hollow-body-hold'],
    progressTo: ['l-sit'],
    needsUpload: true,
  },
  {
    id: 'seated-straddle-lift',
    name: 'Seated Straddle Lift',
    category: 'core',
    difficulty: 'intermediate',
    muscles: ['Hip Flexors', 'Core', 'Adductors'],
    equipment: ['floor'],
    tracks: ['compression'],
    shortPurpose: 'Active compression for straddle positions.',
    description: 'Sit in a straddle, hands on floor between legs, lift feet off floor. Hold.',
    doThis: { setsRange: '4–5', repsRange: '5–10 lifts or 10–20s holds', restSecRange: '60s' },
    thumbnailUrl: 'https://i.ytimg.com/vi/7MNNGqec0Dc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=7MNNGqec0Dc',
    cueStack: ['Hands between legs', 'Lift both feet', 'Keep chest tall'],
    failSigns: ['Rounding back heavily', 'Cannot lift feet', 'Bouncing instead of holding'],
    regressTo: ['tuck-sit', 'hollow-body-hold'],
    progressTo: ['l-sit'],
  },

  // ==================== SKILLS (existing + flag/lever) ====================
  {
    id: 'frog-stand',
    name: 'Frog Stand',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Core', 'Shoulders', 'Wrists'],
    equipment: ['floor'],
    tracks: ['planche', 'general'],
    shortPurpose: 'Balance on hands with knee support.',
    description: 'The foundational balance skill that builds wrist strength and body awareness for advanced hand balancing.',
    image: frogStandImg,
    doThis: { setsRange: '4–5', timeSecRange: '10–30s', restSecRange: '45–60s' },
    cueStack: ['Knees on triceps', 'Lean forward slowly', 'Gaze slightly forward'],
    failSigns: ['Tipping forward', 'Wrist pain', 'Not leaning enough'],
    regressTo: [],
    progressTo: ['planche-lean', 'elbow-lever'],
  },
  {
    id: 'elbow-lever',
    name: 'Elbow Lever',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Core', 'Shoulders', 'Wrists'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Horizontal balance on one/two elbows.',
    description: 'A horizontal balance hold that creates the illusion of defying gravity.',
    image: elbowLeverImg,
    doThis: { setsRange: '4–5', timeSecRange: '10–20s', restSecRange: '60s' },
    cueStack: ['Elbow in hip crease', 'Lean forward', 'Spread fingers wide'],
    failSigns: ['Tipping sideways', 'Elbow slipping', 'Not enough lean'],
    regressTo: ['frog-stand'],
    progressTo: ['single-arm-elbow-lever'],
  },
  {
    id: 'single-arm-elbow-lever',
    name: 'Single Arm Elbow Lever',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Core', 'Shoulder', 'Wrist'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'One-arm horizontal balance.',
    description: 'The ultimate elbow lever progression—balancing your entire body on one arm.',
    image: singleArmElbowLeverImg,
    doThis: { setsRange: '4–6', timeSecRange: '3–10s', restSecRange: '90s' },
    cueStack: ['Shift weight to one arm', 'Extend free arm', 'Full body tension'],
    failSigns: ['Losing balance instantly', 'Wrist strain', 'No body tension'],
    regressTo: ['elbow-lever'],
    progressTo: [],
  },
  {
    id: 'back-lever',
    name: 'Back Lever',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Biceps'],
    equipment: ['pull-up bar', 'rings'],
    tracks: ['rings', 'pull-strength'],
    shortPurpose: 'Straight-arm pulling hold.',
    description: 'Hang face-down with body horizontal. Arms straight, full body tension.',
    doThis: { setsRange: '4–6', timeSecRange: '8–20s', restSecRange: '90–120s' },
    cueStack: ['Straight arms', 'Hollow body', 'Depress shoulders'],
    failSigns: ['Bent arms', 'Hips dropping', 'Shoulder pain'],
    regressTo: ['skin-the-cat'],
    progressTo: ['front-lever'],
    needsUpload: true,
  },
  {
    id: 'front-lever',
    name: 'Front Lever',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Lats', 'Core', 'Shoulders'],
    equipment: ['pull-up bar', 'rings'],
    tracks: ['pull-strength'],
    shortPurpose: 'Full body horizontal pull hold.',
    description: 'Hang face-up with body horizontal. Straight arms, extreme lat and core demand.',
    doThis: { setsRange: '5–8', timeSecRange: '3–12s', restSecRange: '120s' },
    cueStack: ['Depress shoulders', 'Straight arms', 'Squeeze glutes'],
    failSigns: ['Hips dropping', 'Arms bending', 'Losing body tension'],
    regressTo: ['front-lever-raise', 'back-lever'],
    progressTo: [],
    needsUpload: true,
  },
  {
    id: 'human-flag',
    name: 'Human Flag',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Obliques', 'Shoulders', 'Lats', 'Grip'],
    equipment: ['pull-up bar'],
    tracks: ['flag'],
    shortPurpose: 'Lateral body hold on a pole.',
    description: 'An impressive display of lateral core strength and shoulder stability.',
    image: clutchFlagImg,
    instagramUrl: 'https://www.instagram.com/p/DTHBsV-jtej/',
    doThis: { setsRange: '4–6', timeSecRange: '3–10s', restSecRange: '120s' },
    cueStack: ['Bottom arm pushes', 'Top arm pulls', 'Full body straight'],
    failSigns: ['Hips dropping', 'Bending at waist', 'Grip failure'],
    regressTo: ['clutch-flag'],
    progressTo: [],
  },
  {
    id: 'clutch-flag',
    name: 'Clutch Flag',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Obliques', 'Lats', 'Shoulders'],
    equipment: ['pull-up bar'],
    tracks: ['flag'],
    shortPurpose: 'Flag variation with clutch grip.',
    description: 'A horizontal flag variation performed on a vertical bar with a unique grip.',
    image: clutchFlagImg,
    doThis: { setsRange: '4–6', timeSecRange: '3–8s', restSecRange: '120s' },
    cueStack: ['Underhand top, overhand bottom', 'Pull + push simultaneously', 'Body straight'],
    failSigns: ['Hips dropping', 'Grip slipping', 'Bending at waist'],
    regressTo: [],
    progressTo: ['human-flag'],
  },
  {
    id: 'bent-arm-handstand',
    name: 'Bent Arm Handstand',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Triceps', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['handstand'],
    shortPurpose: 'Crocodile-style HS pressing.',
    description: 'A crocodile-style handstand that requires tremendous tricep and shoulder strength.',
    image: bentArmHandstandImg,
    doThis: { setsRange: '4–6', timeSecRange: '3–10s', restSecRange: '120s' },
    cueStack: ['Elbows bent 90°', 'Head close to ground', 'Balance through wrists'],
    failSigns: ['Collapsing', 'No balance control', 'Elbow pain'],
    regressTo: ['freestanding-handstand', 'tiger-bend-pushup'],
    progressTo: [],
  },

  // ==================== HANDSTAND TRACK ADDITIONS ====================
  {
    id: 'straddle-hs-kick-up',
    name: 'Straddle Handstand Kick-Ups',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Shoulders', 'Core', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['handstand'],
    shortPurpose: 'Consistent handstand entry technique.',
    description: 'A straddle-leg kick-up for controlled handstand entry. Develops coordination and reduces fear of inversion.',
    thumbnailUrl: 'https://i.ytimg.com/vi/9Qa5aBZHBvE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9Qa5aBZHBvE',
    doThis: { setsRange: '5–8', repsRange: '3–6', restSecRange: '30–60s' },
    cueStack: ['Straddle legs wide on kick', 'Hands shoulder-width', 'Stack hips over shoulders'],
    failSigns: ['Kicking too hard past vertical', 'Feet together on entry', 'Collapsing on landing'],
    regressTo: ['chest-to-wall-handstand'],
    progressTo: ['freestanding-handstand', 'wall-pull-aways'],
  },
  {
    id: 'handstand-bail',
    name: 'Handstand Exits / Bail-Outs',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Wrists'],
    equipment: ['floor'],
    tracks: ['handstand'],
    shortPurpose: 'Safe handstand exit to overcome fear.',
    description: 'Learn to safely exit a handstand via cartwheel turn-out or pirouette bail. Eliminates fear of falling and enables confident freestanding practice.',
    thumbnailUrl: 'https://i.ytimg.com/vi/Odji8zFBCok/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Odji8zFBCok',
    doThis: { setsRange: '5–8', repsRange: '3–5 each side', restSecRange: '30s' },
    cueStack: ['Turn hand, step down to side', 'Keep arms straight during bail', 'Land on feet, not knees'],
    failSigns: ['Falling flat on back', 'Panicking mid-bail', 'Landing on hands and knees'],
    regressTo: ['chest-to-wall-handstand'],
    progressTo: ['freestanding-handstand'],
  },

  // ==================== FOREARM STAND (PINCHA) TRACK ====================
  {
    id: 'dolphin-pose',
    name: 'Dolphin Pose',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Shoulders', 'Core', 'Hamstrings'],
    equipment: ['floor'],
    tracks: ['forearm-stand', 'yoga-flow'],
    shortPurpose: 'Shoulder opener and Pincha prep.',
    description: 'Forearm down-dog position. Builds the shoulder opening and scapular strength needed for forearm stand.',
    thumbnailUrl: 'https://i.ytimg.com/vi/TavTs7ZcDYM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=TavTs7ZcDYM',
    doThis: { setsRange: '3–4', timeSecRange: '20–45s', restSecRange: '30–45s' },
    cueStack: ['Forearms parallel on floor', 'Push hips high', 'Head between arms'],
    failSigns: ['Shoulders dumping toward floor', 'Elbows splaying out', 'Lower back rounding'],
    regressTo: ['downward-dog'],
    progressTo: ['forearm-stand-toe-pulls'],
  },
  {
    id: 'forearm-stand-toe-pulls',
    name: 'Forearm Stand Toe Pulls',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Core', 'Traps'],
    equipment: ['wall'],
    tracks: ['forearm-stand'],
    shortPurpose: 'Wall balance drill for Pincha.',
    description: 'In a wall-supported forearm stand, gently pull toes off the wall to train balance. Develops the shoulder and core control for freestanding Pincha.',
    thumbnailUrl: 'https://i.ytimg.com/vi/j5XfbRA12yg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=j5XfbRA12yg',
    doThis: { setsRange: '5–8', timeSecRange: '2–5s per pull', restSecRange: '30–60s' },
    cueStack: ['Elbows under shoulders', 'Gentle toe-off from wall', 'Press forearms into floor'],
    failSigns: ['Elbows splaying wider than shoulders', 'Falling sideways immediately', 'Arching lower back'],
    regressTo: ['dolphin-pose'],
    progressTo: ['forearm-stand-line-hold'],
  },
  {
    id: 'forearm-stand-line-hold',
    name: 'Forearm Stand Line Holds',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Shoulders', 'Core', 'Traps', 'Serratus'],
    equipment: ['floor'],
    tracks: ['forearm-stand'],
    shortPurpose: 'Freestanding Pincha balance.',
    description: 'A straight-line forearm stand held away from the wall. The culmination of Pincha training—demands shoulder stability and refined balance.',
    thumbnailUrl: 'https://i.ytimg.com/vi/emCch6a0DV4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=emCch6a0DV4',
    doThis: { setsRange: '6–10 attempts', timeSecRange: '3–15s', restSecRange: '30–60s' },
    cueStack: ['Stack hips over shoulders', 'Push forearms into floor', 'Squeeze glutes to close the line'],
    failSigns: ['Banana back', 'Elbows sliding out', 'No balance corrections'],
    regressTo: ['forearm-stand-toe-pulls'],
    progressTo: [],
  },

  // ==================== ELBOW STAND TRACK ====================
  {
    id: 'elbow-stand-wall-hold',
    name: 'Elbow Stand Wall Holds',
    category: 'skills',
    difficulty: 'beginner',
    muscles: ['Triceps', 'Shoulders', 'Core'],
    equipment: ['wall'],
    tracks: ['elbow-stand'],
    shortPurpose: 'Wall-supported elbow balance intro.',
    description: 'Practice an elbow stand against a wall to build the tricep strength and balance awareness needed for freestanding elbow stands.',
    thumbnailUrl: 'https://i.ytimg.com/vi/rCbUwZe-naU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=rCbUwZe-naU',
    doThis: { setsRange: '4–6', timeSecRange: '10–30s', restSecRange: '60s' },
    cueStack: ['Hands flat, elbows bent', 'Weight in palms and forearms', 'Core tight, ribs in'],
    failSigns: ['Collapsing onto head', 'Elbows flaring wide', 'Lower back arching'],
    regressTo: ['headstand'],
    progressTo: ['elbow-stand-straddle-entry'],
  },
  {
    id: 'elbow-stand-straddle-entry',
    name: 'Elbow Stand Straddle Entry',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Triceps', 'Shoulders', 'Core', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['elbow-stand'],
    shortPurpose: 'Controlled elbow stand kick-up.',
    description: 'A straddle-leg entry into elbow stand that develops control and reduces the momentum needed compared to a straight-leg kick.',
    thumbnailUrl: 'https://i.ytimg.com/vi/fTVaAFnYPpg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=fTVaAFnYPpg',
    doThis: { setsRange: '5–8', repsRange: '3–5', restSecRange: '45–60s' },
    cueStack: ['Straddle wide on kick', 'Press through palms', 'Stack hips then close legs'],
    failSigns: ['Over-kicking past balance', 'Collapsing onto head', 'No straddle control'],
    regressTo: ['elbow-stand-wall-hold'],
    progressTo: ['elbow-stand-exit'],
  },
  {
    id: 'elbow-stand-exit',
    name: 'Elbow Stand Exits',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Triceps', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['elbow-stand'],
    shortPurpose: 'Safe dismount from elbow stand.',
    description: 'Learn to safely exit an elbow stand by rolling out or stepping down. Protects the face and neck and builds confidence for longer holds.',
    thumbnailUrl: 'https://i.ytimg.com/vi/56EA69T30lA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=56EA69T30lA',
    doThis: { setsRange: '5–8', repsRange: '3–5', restSecRange: '30s' },
    cueStack: ['Tuck chin on exit', 'Roll through upper back', 'Control the descent speed'],
    failSigns: ['Landing on face', 'Flopping uncontrolled', 'Neck strain'],
    regressTo: ['elbow-stand-wall-hold'],
    progressTo: [],
  },

  // ==================== GRIP TRACK ====================
  {
    id: 'dead-hang',
    name: 'Dead Hang',
    category: 'pull',
    difficulty: 'easy',
    muscles: ['Grip', 'Forearms', 'Shoulders'],
    equipment: ['pull-up bar'],
    tracks: ['grip', 'pull-strength'],
    shortPurpose: 'Baseline grip and shoulder health.',
    description: 'Hang from a bar with relaxed shoulders (passive) or depressed shoulders (active). Builds grip endurance and decompresses the spine.',
    thumbnailUrl: 'https://i.ytimg.com/vi/ibCEOkMqrTM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ibCEOkMqrTM',
    doThis: { setsRange: '3–4', timeSecRange: '20–60s', restSecRange: '45–60s' },
    cueStack: ['Full grip around bar', 'Relax shoulders (passive) or depress (active)', 'Breathe normally'],
    failSigns: ['Grip slipping before time', 'Shoulders shrugged to ears entire time', 'Swinging'],
    regressTo: [],
    progressTo: ['towel-hang', 'chin-up'],
  },
  {
    id: 'towel-hang',
    name: 'Towel Hang',
    category: 'pull',
    difficulty: 'beginner',
    muscles: ['Grip', 'Forearms', 'Shoulders'],
    equipment: ['pull-up bar', 'towel'],
    tracks: ['grip'],
    shortPurpose: 'Advanced grip via thick, unstable surface.',
    description: 'Hang from a towel draped over a pull-up bar. The thick, pliable surface forces forearms to work significantly harder than a standard bar hang.',
    thumbnailUrl: 'https://i.ytimg.com/vi/gvgpRes6FwA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=gvgpRes6FwA',
    doThis: { setsRange: '3–4', timeSecRange: '15–40s', restSecRange: '60s' },
    cueStack: ['Grip towel tightly', 'Shoulders depressed', 'No swinging'],
    failSigns: ['Slipping off towel', 'Grip failing under 10s', 'Using momentum'],
    regressTo: ['dead-hang'],
    progressTo: [],
  },
  {
    id: 'extensor-band',
    name: 'Extensor Band Exercises',
    category: 'mobility',
    difficulty: 'easy',
    muscles: ['Forearm Extensors', 'Fingers'],
    equipment: ['resistance band'],
    tracks: ['grip'],
    shortPurpose: 'Balance grip by training extensors.',
    description: 'Use finger extensor bands to strengthen the often-neglected forearm extensors. Prevents imbalances from heavy grip work and reduces elbow injury risk.',
    thumbnailUrl: 'https://i.ytimg.com/vi/N13X8VhA1ZE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=N13X8VhA1ZE',
    doThis: { setsRange: '2–3', repsRange: '15–25', restSecRange: '30s' },
    cueStack: ['Spread fingers against band', 'Full extension each rep', 'Controlled tempo'],
    failSigns: ['Rushing reps', 'Partial extension', 'No resistance felt'],
    regressTo: [],
    progressTo: [],
  },

  // ==================== COMPRESSION ADDITIONS ====================
  {
    id: 'seated-pike-lift',
    name: 'Seated Pike Compression Lifts',
    category: 'core',
    difficulty: 'beginner',
    muscles: ['Hip Flexors', 'Core', 'Quadriceps'],
    equipment: ['floor'],
    tracks: ['compression'],
    shortPurpose: 'Active pike compression for L-sit prep.',
    description: 'Seated with legs together and straight, lift both feet off the floor using hip flexors. Builds the active compression needed for L-sit and press handstand.',
    thumbnailUrl: 'https://i.ytimg.com/vi/WR3C2cliSaA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=WR3C2cliSaA',
    doThis: { setsRange: '3–4', repsRange: '8–15 lifts or 10–20s holds', restSecRange: '45–60s' },
    cueStack: ['Knees locked straight', 'Chest tall, lean slightly forward', 'Lift from hip flexors'],
    failSigns: ['Bending knees to lift', 'Rounding back completely', 'Cannot lift feet at all'],
    regressTo: ['hollow-body-hold'],
    progressTo: ['seated-straddle-lift', 'l-sit'],
  },

  // ==================== LEGS ADDITIONS ====================
  {
    id: 'lunge',
    name: 'Lunges',
    category: 'legs',
    difficulty: 'easy',
    muscles: ['Quadriceps', 'Glutes', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['legs', 'general'],
    shortPurpose: 'Unilateral leg pattern and hip stability.',
    description: 'Forward or reverse lunge with control. Develops single-leg strength, balance, and hip stability as a foundation for pistol and shrimp squat progressions.',
    thumbnailUrl: 'https://i.ytimg.com/vi/7pkeQFzJR9g/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=7pkeQFzJR9g',
    doThis: { setsRange: '3', repsRange: '10–15 each', restSecRange: '45–60s' },
    cueStack: ['Step length allows 90° at both knees', 'Upright torso', 'Control the descent'],
    failSigns: ['Knee shooting past toes', 'Torso collapsing forward', 'Losing balance each rep'],
    regressTo: ['bodyweight-squat'],
    progressTo: ['bulgarian-split-squat'],
  },
  {
    id: 'cossack-squat',
    name: 'Cossack Squat',
    category: 'legs',
    difficulty: 'beginner',
    muscles: ['Quadriceps', 'Adductors', 'Glutes', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['legs'],
    shortPurpose: 'Lateral mobility and unilateral strength.',
    description: 'A deep side-to-side squat that develops hip mobility, adductor flexibility, and single-leg strength. Essential for well-rounded lower body development.',
    thumbnailUrl: 'https://i.ytimg.com/vi/tpczTeSkHz0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=tpczTeSkHz0',
    doThis: { setsRange: '3', repsRange: '6–10 each', restSecRange: '60s' },
    cueStack: ['Heel down on working leg', 'Chest up', 'Straight leg toes point up'],
    failSigns: ['Heel lifting', 'Rounding back at bottom', 'Knee caving inward'],
    regressTo: ['bodyweight-squat', 'deep-squat-hold'],
    progressTo: ['pistol-squat'],
  },

  // ==================== INSTAGRAM REEL EXERCISES ====================
  {
    id: 'wall-compression-stretch',
    name: 'Wall Compression Stretch',
    category: 'core',
    difficulty: 'beginner',
    muscles: ['Hip Flexors', 'Core', 'Hamstrings'],
    equipment: ['wall'],
    tracks: ['compression', 'press'],
    shortPurpose: 'Wall-assisted active pike compression.',
    description: 'Face a wall, place feet up the wall and actively compress chest to thighs. Builds the deep pike compression needed for press to handstand.',
    creator: '@alessiakoff',
    instagramUrl: 'https://www.instagram.com/p/DVbYLGDjE1T/',
    doThis: { setsRange: '3–4', timeSecRange: '20–45s', restSecRange: '60s' },
    cueStack: ['Chest to thighs', 'Straight legs against wall', 'Breathe into the fold'],
    failSigns: ['Rounding upper back instead of hinging', 'Bent knees', 'Holding breath'],
    regressTo: ['seated-pike-lift'],
    progressTo: ['elevated-chair-compression'],
  },
  {
    id: 'elevated-chair-compression',
    name: 'Elevated Chair Compression Drill',
    category: 'core',
    difficulty: 'intermediate',
    muscles: ['Hip Flexors', 'Core', 'Shoulders'],
    equipment: ['chair'],
    tracks: ['compression', 'press'],
    shortPurpose: 'Elevated compression for press handstand.',
    description: 'Hands on a chair/blocks, actively compress and lift legs in pike or straddle. The elevated surface allows deeper compression range.',
    creator: '@balancenotion',
    instagramUrl: 'https://www.instagram.com/p/DUQhN8pFHm9/',
    doThis: { setsRange: '3–4', repsRange: '5–10 lifts or 15–30s holds', restSecRange: '60–90s' },
    cueStack: ['Depress shoulders on blocks', 'Squeeze legs to chest', 'Lift hips above shoulders'],
    failSigns: ['Shoulders shrugging', 'Cannot lift hips', 'Losing compression at top'],
    regressTo: ['wall-compression-stretch', 'seated-pike-lift'],
    progressTo: ['straddle-press-to-hs'],
  },
  {
    id: 'crocodile-pose',
    name: 'Crocodile Pose (One-Arm Balance)',
    category: 'skills',
    difficulty: 'intermediate',
    muscles: ['Core', 'Shoulders', 'Wrists', 'Obliques'],
    equipment: ['floor'],
    tracks: ['general'],
    shortPurpose: 'Asymmetric arm balance challenge.',
    description: 'A one-arm balance where the body extends laterally like a crocodile. Demands wrist strength, oblique engagement, and fearless lean.',
    creator: '@balancenotion',
    instagramUrl: 'https://www.instagram.com/p/DUHXfxxiFYL/',
    doThis: { setsRange: '4–6', timeSecRange: '5–15s each side', restSecRange: '60–90s' },
    cueStack: ['Elbow in hip crease', 'Extend legs back and to side', 'Lean until you float'],
    failSigns: ['Tipping over', 'Wrist pain', 'No extension in legs'],
    regressTo: ['elbow-lever', 'frog-stand'],
    progressTo: ['single-arm-elbow-lever'],
  },
  {
    id: 'hspu-capacity-builder',
    name: 'HSPU Capacity Builder',
    category: 'push',
    difficulty: 'intermediate',
    muscles: ['Shoulders', 'Triceps', 'Core', 'Traps'],
    equipment: ['wall'],
    tracks: ['handstand'],
    shortPurpose: 'Volume work for handstand push-up strength.',
    description: 'Wall-supported partial-range handstand push-up drills focusing on building pressing capacity. Eccentric-focused negatives and pause reps.',
    creator: '@andry_strong',
    instagramUrl: 'https://www.instagram.com/p/DU5jYLADGCp/',
    doThis: { setsRange: '4–5', repsRange: '3–8', restSecRange: '90–120s' },
    cueStack: ['Slow eccentrics (3–5s down)', 'Pause at bottom', 'Press through full ROM'],
    failSigns: ['Crashing down uncontrolled', 'Arching lower back', 'No pause at bottom'],
    regressTo: ['pike-push-up', 'chest-to-wall-handstand'],
    progressTo: ['handstand-push-up'],
  },
  {
    id: 'band-assisted-progressions',
    name: 'Band-Assisted Progressions',
    category: 'push',
    difficulty: 'easy',
    muscles: ['Shoulders', 'Core', 'Chest'],
    equipment: ['resistance band', 'floor'],
    tracks: ['general'],
    shortPurpose: 'Use bands to train advanced moves safely.',
    description: 'Resistance band assistance for planche leans, front lever attempts, and other advanced holds. Allows proper form practice before full bodyweight.',
    creator: '@cali.maxi',
    instagramUrl: 'https://www.instagram.com/p/DUB-JFgDZtn/',
    doThis: { setsRange: '3–5', timeSecRange: '10–30s', restSecRange: '60–90s' },
    cueStack: ['Band at hips for support', 'Maintain proper form despite assistance', 'Gradually reduce band tension'],
    failSigns: ['Relying entirely on band', 'Losing form because band compensates', 'Band snapping back'],
    regressTo: [],
    progressTo: ['planche-lean', 'front-lever-raise'],
  },

  // ==================== PRESS HANDSTAND EXERCISES ====================
  {
    id: 'straddle-press-to-hs',
    name: 'Straddle Press to Handstand',
    category: 'skills',
    difficulty: 'advanced',
    muscles: ['Shoulders', 'Core', 'Hip Flexors', 'Hamstrings'],
    equipment: ['floor'],
    tracks: ['press', 'handstand', 'compression'],
    shortPurpose: 'Controlled straddle-leg press into handstand.',
    description: 'From standing straddle, fold forward, place hands, and press up through a straddle to handstand with straight arms. The ultimate compression strength demonstration.',
    instagramUrl: 'https://www.instagram.com/p/DUYkMZJDHsk/',
    doThis: { setsRange: '5–8', repsRange: '1–5', restSecRange: '120s' },
    cueStack: ['Lean forward as hips rise', 'Straight arms throughout', 'Straddle legs until vertical then close'],
    failSigns: ['Bending arms', 'Jumping instead of pressing', 'Losing balance mid-press'],
    regressTo: ['elevated-chair-compression', 'l-sit'],
    progressTo: ['stalder-press-to-hs'],
  },
  {
    id: 'stalder-press-to-hs',
    name: 'Stalder Press to Handstand',
    category: 'skills',
    difficulty: 'master',
    muscles: ['Shoulders', 'Core', 'Hip Flexors', 'Adductors'],
    equipment: ['floor'],
    tracks: ['press', 'handstand', 'compression'],
    shortPurpose: 'Closed-leg straddle press — elite compression.',
    description: 'From a seated straddle on the floor, press to handstand without jumping. Requires extreme compression strength and shoulder leverage. The pinnacle of press handstand mastery.',
    instagramUrl: 'https://www.instagram.com/p/DUNizecjNBl/',
    doThis: { setsRange: '5–8', repsRange: '1–3', restSecRange: '180s' },
    cueStack: ['Start from floor straddle', 'Lean hard forward', 'Compress and lift without momentum'],
    failSigns: ['Using momentum/bounce', 'Arms bending', 'Cannot clear floor'],
    regressTo: ['straddle-press-to-hs'],
    progressTo: [],
  },

  // ==================== YOGA POSES ====================
  {
    id: 'childs-pose',
    name: "Child's Pose",
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Spine', 'Hips', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Resting position and spinal release.',
    description: 'Kneel, sit back on heels, fold forward with arms extended. The universal rest and reset position.',
    doThis: { setsRange: '1–3', timeSecRange: '30–90s', restSecRange: '—' },
    cueStack: ['Knees together or wide', 'Hips to heels', 'Forehead to floor'],
    failSigns: ['Hips lifting off heels', 'Tension in shoulders', 'Holding breath'],
    regressTo: [],
    progressTo: ['cat-cow-stretch'],
  },
  {
    id: 'warrior-i',
    name: 'Warrior I (Virabhadrasana I)',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Quadriceps', 'Hip Flexors', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Standing strength + hip opening.',
    description: 'Deep lunge with back foot angled, arms reaching overhead. Builds leg strength and hip flexibility.',
    doThis: { setsRange: '2–3', timeSecRange: '30–60s each side', restSecRange: '15s' },
    cueStack: ['Back foot at 45°', 'Front knee over ankle', 'Arms reach high, shoulders down'],
    failSigns: ['Back heel lifting', 'Front knee past toes', 'Shoulders at ears'],
    regressTo: ['childs-pose'],
    progressTo: ['warrior-ii'],
  },
  {
    id: 'warrior-ii',
    name: 'Warrior II (Virabhadrasana II)',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Quadriceps', 'Hips', 'Shoulders', 'Core'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Open-hip warrior stance.',
    description: 'Wide stance, front knee bent, arms extended parallel to floor. Gaze over front fingers.',
    doThis: { setsRange: '2–3', timeSecRange: '30–60s each side', restSecRange: '15s' },
    cueStack: ['Front knee tracks over toes', 'Arms level, shoulders relaxed', 'Gaze past front hand'],
    failSigns: ['Front knee caving in', 'Leaning torso forward', 'Arms drooping'],
    regressTo: ['warrior-i'],
    progressTo: ['warrior-iii', 'triangle-pose'],
  },
  {
    id: 'warrior-iii',
    name: 'Warrior III (Virabhadrasana III)',
    category: 'yoga',
    difficulty: 'intermediate',
    muscles: ['Hamstrings', 'Glutes', 'Core', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Single-leg balance + posterior chain.',
    description: 'Standing on one leg, torso and back leg form a T-shape. Arms extend forward or alongside body.',
    doThis: { setsRange: '2–3', timeSecRange: '15–30s each side', restSecRange: '30s' },
    cueStack: ['Hips level and square', 'Back leg active', 'Core engaged, no arching'],
    failSigns: ['Hip opening to side', 'Standing knee locking hyperextended', 'Falling out immediately'],
    regressTo: ['warrior-ii', 'tree-pose'],
    progressTo: ['half-moon-pose'],
  },
  {
    id: 'tree-pose',
    name: 'Tree Pose (Vrksasana)',
    category: 'yoga',
    difficulty: 'easy',
    muscles: ['Core', 'Hips', 'Ankles', 'Glutes'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Standing balance and focus.',
    description: 'Stand on one leg, place other foot on inner thigh or calf (never the knee). Hands at heart or overhead.',
    doThis: { setsRange: '2–3', timeSecRange: '30–60s each side', restSecRange: '15s' },
    cueStack: ['Foot presses into thigh, thigh presses back', 'Hips level', 'Gaze fixed on one point'],
    failSigns: ['Foot on knee joint', 'Hips uneven', 'Losing focus and wobbling'],
    regressTo: ['childs-pose'],
    progressTo: ['warrior-iii'],
  },
  {
    id: 'chair-pose',
    name: 'Chair Pose (Utkatasana)',
    category: 'yoga',
    difficulty: 'beginner',
    muscles: ['Quadriceps', 'Glutes', 'Core', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Standing squat hold with overhead reach.',
    description: 'Sit back as if into a chair, arms reaching overhead. Builds leg endurance and core stability.',
    doThis: { setsRange: '2–3', timeSecRange: '20–45s', restSecRange: '30s' },
    cueStack: ['Weight in heels', 'Knees behind toes', 'Arms by ears, shoulders down'],
    failSigns: ['Knees past toes', 'Arching lower back', 'Arms dropping'],
    regressTo: ['warrior-i'],
    progressTo: ['warrior-iii'],
  },
  {
    id: 'triangle-pose',
    name: 'Triangle Pose (Trikonasana)',
    category: 'yoga',
    difficulty: 'beginner',
    muscles: ['Hamstrings', 'Obliques', 'Hips', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Lateral stretch and hip opener.',
    description: 'Wide stance, hinge at hip to reach one hand toward foot while other arm reaches skyward. Opens the entire side body.',
    doThis: { setsRange: '2–3', timeSecRange: '30–45s each side', restSecRange: '15s' },
    cueStack: ['Hinge from hip, not waist', 'Both arms in one line', 'Gaze up at top hand'],
    failSigns: ['Rounding toward floor', 'Knee locking hyperextended', 'Shoulders collapsing'],
    regressTo: ['warrior-ii'],
    progressTo: ['half-moon-pose'],
  },
  {
    id: 'crow-pose',
    name: 'Crow Pose (Bakasana)',
    category: 'yoga',
    difficulty: 'intermediate',
    muscles: ['Core', 'Shoulders', 'Wrists', 'Hip Flexors'],
    equipment: ['floor'],
    tracks: ['yoga-flow', 'planche'],
    shortPurpose: 'Arm balance bridging yoga and calisthenics.',
    description: 'Squat, place hands on floor, lean forward and lift feet. The gateway arm balance that connects yoga to planche progression.',
    doThis: { setsRange: '4–6', timeSecRange: '5–20s', restSecRange: '60s' },
    cueStack: ['Knees on backs of arms', 'Lean forward until feet lift', 'Gaze slightly forward'],
    failSigns: ['Face-planting', 'Wrist pain', 'Not leaning enough'],
    regressTo: ['frog-stand'],
    progressTo: ['planche-lean', 'crane-pose'],
  },
  {
    id: 'half-moon-pose',
    name: 'Half Moon Pose (Ardha Chandrasana)',
    category: 'yoga',
    difficulty: 'intermediate',
    muscles: ['Glutes', 'Core', 'Hamstrings', 'Ankles'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Open-hip balance on one leg.',
    description: 'Balance on one leg with torso and lifted leg parallel to floor, top arm reaching skyward. Demands balance, hip opening, and core stability.',
    doThis: { setsRange: '2–3', timeSecRange: '15–30s each side', restSecRange: '30s' },
    cueStack: ['Stack hips vertically', 'Flex lifted foot', 'Gaze up at top hand'],
    failSigns: ['Standing hip collapsing', 'Closing off top hip', 'Losing balance immediately'],
    regressTo: ['triangle-pose', 'warrior-iii'],
    progressTo: [],
  },
  {
    id: 'wheel-pose',
    name: 'Wheel Pose (Urdhva Dhanurasana)',
    category: 'yoga',
    difficulty: 'advanced',
    muscles: ['Spine', 'Shoulders', 'Glutes', 'Quadriceps'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Full backbend — spinal extension peak.',
    description: 'Full back bridge pushing up from floor. Demands shoulder mobility, spinal extension, and hip flexor openness. The advanced expression of bridge pose.',
    doThis: { setsRange: '3–4', timeSecRange: '10–30s', restSecRange: '60–90s' },
    cueStack: ['Push through hands and feet', 'Straighten arms', 'Press chest through arms'],
    failSigns: ['Cannot straighten arms', 'Pain in lower back', 'Feet turning out'],
    regressTo: ['bridge-pose', 'cobra-pose'],
    progressTo: [],
  },
  {
    id: 'camel-pose',
    name: 'Camel Pose (Ustrasana)',
    category: 'yoga',
    difficulty: 'beginner',
    muscles: ['Spine', 'Hip Flexors', 'Chest', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['yoga-flow'],
    shortPurpose: 'Kneeling backbend and chest opener.',
    description: 'Kneel, place hands on heels, and push hips forward while arching back. Opens the entire front body.',
    doThis: { setsRange: '2–3', timeSecRange: '15–30s', restSecRange: '30s' },
    cueStack: ['Push hips forward over knees', 'Lift chest before arching', 'Head follows the arc naturally'],
    failSigns: ['Hips behind knees', 'Compressing lower back', 'Neck dropping too fast'],
    regressTo: ['cobra-pose'],
    progressTo: ['wheel-pose'],
  },

  // ==================== ADDITIONAL IG REEL REFERENCES ====================
  // Remaining IG links attached to relevant existing/new exercises
  {
    id: 'press-hs-journey',
    name: 'Press Handstand Journey Drills',
    category: 'core',
    difficulty: 'intermediate',
    muscles: ['Hip Flexors', 'Core', 'Shoulders'],
    equipment: ['floor'],
    tracks: ['press', 'compression'],
    shortPurpose: 'Combo drills for press handstand progression.',
    description: 'A collection of drills combining pike compression, straddle lifts, and wall walks to build the specific strength for press to handstand.',
    instagramUrl: 'https://www.instagram.com/p/DUAYzFAkr_T/',
    doThis: { setsRange: '3–4', repsRange: '5–8 each drill', restSecRange: '60–90s' },
    cueStack: ['Focus on compression, not momentum', 'Straight arms always', 'Quality over quantity'],
    failSigns: ['Using momentum', 'Bent arms', 'Skipping the hard part'],
    regressTo: ['seated-pike-lift', 'wall-compression-stretch'],
    progressTo: ['straddle-press-to-hs'],
  },
];

// Helper functions
export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
export const getExercisesByCategory = (cat: string) => exercises.filter(e => e.category === cat);
export const getExercisesByTrack = (track: string) => exercises.filter(e => e.tracks.includes(track as any));
export const getExercisesByDifficulty = (diff: string) => exercises.filter(e => e.difficulty === diff);
export const getExercisesByEquipment = (equip: string[]) =>
  exercises.filter(e => e.equipment.every(eq => equip.includes(eq)));
