// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-workout-logs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      content: [
        { type: "text", text: "Not authenticated. Connect this app with your account first." }
      ],
      isError: true
    };
  }
  return null;
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-workout-logs.ts
var list_workout_logs_default = defineTool({
  name: "list_workout_logs",
  title: "List workout logs",
  description: "List the signed-in athlete's logged training sets, newest first. Optionally filter by date range (YYYY-MM-DD).",
  inputSchema: {
    from: z.string().optional().describe("Earliest log date, YYYY-MM-DD."),
    to: z.string().optional().describe("Latest log date, YYYY-MM-DD."),
    limit: z.number().int().optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const take = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("workout_logs").select("id,logged_at,exercise_id,exercise_name,sets,reps,duration_seconds,notes").order("logged_at", { ascending: false }).order("created_at", { ascending: false }).limit(take);
    if (from) query = query.gte("logged_at", from);
    if (to) query = query.lte("logged_at", to);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, logs: data ?? [] });
  }
});

// src/lib/mcp/tools/log-workout.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var log_workout_default = defineTool2({
  name: "log_workout",
  title: "Log a workout set",
  description: "Log a training entry for the signed-in athlete: exercise name, date, and any of sets, reps, duration, notes.",
  inputSchema: {
    exercise_name: z2.string().describe("Human-readable exercise name, e.g. 'Hollow Body Hold'."),
    exercise_id: z2.string().optional().describe("Slug id from the app's library if known, e.g. 'hollow-body-hold'."),
    logged_at: z2.string().optional().describe("Date of the session, YYYY-MM-DD. Defaults to today (UTC)."),
    sets: z2.number().int().optional().describe("Number of sets performed."),
    reps: z2.number().int().optional().describe("Reps per set."),
    duration_seconds: z2.number().int().optional().describe("Hold or work duration in seconds."),
    notes: z2.string().optional().describe("Free-form coaching notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const name = input.exercise_name.trim();
    if (!name) return errorResult("exercise_name cannot be empty.");
    const loggedAt = (input.logged_at ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(loggedAt)) {
      return errorResult("logged_at must be a date in YYYY-MM-DD format.");
    }
    const { data, error } = await supabaseForUser(ctx).from("workout_logs").insert({
      user_id: ctx.getUserId(),
      exercise_name: name,
      exercise_id: input.exercise_id?.trim() || name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      logged_at: loggedAt,
      sets: input.sets ?? null,
      reps: input.reps ?? null,
      duration_seconds: input.duration_seconds ?? null,
      notes: input.notes?.slice(0, 2e3) ?? null
    }).select("id,logged_at,exercise_id,exercise_name,sets,reps,duration_seconds,notes").single();
    if (error) return errorResult(error.message);
    return jsonResult({ created: data });
  }
});

// src/lib/mcp/tools/delete-workout-log.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var delete_workout_log_default = defineTool3({
  name: "delete_workout_log",
  title: "Delete a workout log",
  description: "Permanently delete one of the signed-in athlete's workout log entries by id.",
  inputSchema: {
    id: z3.string().describe("The workout log id (uuid) to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("workout_logs").delete().eq("id", id).select("id");
    if (error) return errorResult(error.message);
    if (!data?.length) return errorResult(`No workout log found with id ${id}.`);
    return jsonResult({ deleted: id });
  }
});

// src/lib/mcp/tools/training-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function currentStreak(dates) {
  const unique = new Set(dates);
  let streak = 0;
  const cursor = /* @__PURE__ */ new Date();
  for (let i = 0; i < 400; i++) {
    const key = cursor.toISOString().slice(0, 10);
    if (unique.has(key)) {
      streak++;
      cursor.setUTCDate(cursor.getUTCDate() - 1);
    } else if (i === 0) {
      cursor.setUTCDate(cursor.getUTCDate() - 1);
    } else break;
  }
  return streak;
}
var training_summary_default = defineTool4({
  name: "training_summary",
  title: "Training summary",
  description: "Summarize the signed-in athlete's recent training: session count, current streak, most-trained exercises, and last session date.",
  inputSchema: {
    days: z4.number().int().optional().describe("Look-back window in days (default 30, max 365).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const window = Math.min(Math.max(days ?? 30, 1), 365);
    const since = /* @__PURE__ */ new Date();
    since.setUTCDate(since.getUTCDate() - window);
    const { data, error } = await supabaseForUser(ctx).from("workout_logs").select("logged_at,exercise_name,sets,reps,duration_seconds").gte("logged_at", since.toISOString().slice(0, 10)).order("logged_at", { ascending: false });
    if (error) return errorResult(error.message);
    const logs = data ?? [];
    const counts = /* @__PURE__ */ new Map();
    for (const l of logs) counts.set(l.exercise_name, (counts.get(l.exercise_name) ?? 0) + 1);
    const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([exercise_name, entries]) => ({ exercise_name, entries }));
    const dates = logs.map((l) => l.logged_at);
    return jsonResult({
      window_days: window,
      total_entries: logs.length,
      distinct_training_days: new Set(dates).size,
      current_streak_days: currentStreak(dates),
      last_session: dates[0] ?? null,
      top_exercises: top
    });
  }
});

// src/lib/mcp/tools/search-exercise-videos.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var search_exercise_videos_default = defineTool5({
  name: "search_exercise_videos",
  title: "Search exercise videos",
  description: "Search the app's exercise video library (TLC TV) by exercise id or keyword and return matching video entries.",
  inputSchema: {
    query: z5.string().describe("Keyword or exercise id to match, e.g. 'planche' or 'clutch-flag'."),
    limit: z5.number().int().optional().describe("Max rows to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const q = query.trim();
    if (!q) return errorResult("query cannot be empty.");
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const { data, error } = await supabaseForUser(ctx).from("exercise_videos").select("*").ilike("exercise_id", `%${q.replace(/[%_]/g, "")}%`).limit(take);
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, videos: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "dqrllgdffkaclpoglbfk";
var mcp_default = defineMcp({
  name: "superhuman-tlc-mcp",
  title: "SUPERHUMAN by TLC",
  version: "0.1.0",
  instructions: "Tools for the SUPERHUMAN hybrid-athlete training app by TLC. Use `training_summary` for an overview of the athlete's recent training, `list_workout_logs` to read logged sets, `log_workout` to record a new set, `delete_workout_log` to remove an entry, and `search_exercise_videos` to find tutorial videos in the app's library. All tools act as the signed-in athlete.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [training_summary_default, list_workout_logs_default, log_workout_default, delete_workout_log_default, search_exercise_videos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
